### ISSUE TITLE
getting error in template

### ISSUE THREAD

**Issue by manojinaction** [Especializa/nativescript-whatsapp-template#1]
getting error when execute:
tns create project-name --template nativescript-whatsapp-template

Error:

fs.js:923
  return binding.mkdir(pathModule._makeLong(path),
                 ^

Error: ENOENT: no such file or directory, mkdir '/Users/manoj/workspace/projects/letsGo/app/fonts'
    at Error (native)
    at Object.fs.mkdirSync (fs.js:923:18)
    at copyFontFile (/Users/manoj/workspace/projects/letsGo/node_modules/nativescript-material-icons/scripts/postinstall.js:10:8)
    at main (/Users/manoj/workspace/projects/letsGo/node_modules/nativescript-material-icons/scripts/postinstall.js:20:3)
    at Object.<anonymous> (/Users/manoj/workspace/projects/letsGo/node_modules/nativescript-material-icons/scripts/postinstall.js:24:1)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
Command npm install nativescript-whatsapp-template@1.0.0 --silent --save-exact --save failed with exit code 1

**Comment by berardo** [comment]
Hi @manojinaction.
This error was due to nativescript-material-icons postinstall script needs to have the app subfolder in order write the material design font file.
Turns out this app folder still doesn't exist at the time the project is being created.
Had tested having an app subfolder in the template but it didn't work (even worse, it ended up creating an app/app folder).
When you opened this issue I believe this problem was fixed but wasn't published on npm so the command to create should have been:
```sh
tns create your-project --template https://github.com/Especializa/nativescript-whatsapp-template
```
Now that the version 1.0.1 is published on npm you can run the normal `tns create` as mentioned on readme and should be able to get it created.
